[reachA] BUG: Fix subscription over system privileges!
This fixes a slew of issues. This resolves similiar issues as seen below:

ReferenceError: Native function [PlayerPlaceBlockBeforeEventSignal::unsubscribe] does not have required privileges

Such reference errors were also preventing the module from working entirely. This patch brings this module inline with standard practices according to the requirements set forth by the API.